name: Extract Boot IMG

on:
  workflow_dispatch:
    inputs:
      rom_link:
        description: The link to the ROM
        type: string
        required: true

jobs:
  extract-boot-img:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Boot IMG
        run: tar -xf "$(curl -sSLOJ --write-out "%{filename_effective}" "${{ inputs.rom_link }}")" --occurrence --wildcards '*/images/boot.img'

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: "**/boot.img"
