name: Keystore Gen

on:
  workflow_dispatch:
    inputs:
      name:
        description: The Keystore Name
        default: release
        type: string
        required: true
      password:
        description: The Keystore Password
        default: androidreleasekey
        type: string
        required: true
      alias:
        description: The Keystore Alias
        default: androidrelease
        type: string
        required: true
      common_name:
        description: The Keystore Common Name
        default: Release
        type: string
        required: true

jobs:
  keystore-gen:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ inputs.name }}
      PASSWORD: ${{ inputs.password }}
      ALIAS: ${{ inputs.alias }}
      COMMON_NAME: ${{ inputs.common_name }}
    steps:
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Generate Keystore
        run: |
          keytool \
            -genkeypair \
            -keyalg RSA \
            -keystore "$NAME.keystore" \
            -keypass "$PASSWORD" \
            -storepass "$PASSWORD" \
            -alias "$ALIAS" \
            -dname "CN=$COMMON_NAME" \
            -validity 9999

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: keystore
          path: "*.keystore"