name: Offline Docs

on:
  workflow_dispatch:
    inputs:
      link:
        description: Link
        type: string
        required: true

jobs:
  offline-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Download Site
        run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent --directory-prefix offline-docs "${{ inputs.link }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: offline-docs
